/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iniciar;

/**
 *
 * @author LAB01
 */
public class clientesConectados extends javax.swing.JFrame {

    /**
     * Creates new form clientesConectados
     */
    public clientesConectados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanneDialogCliente = new javax.swing.JTabbedPane();
        painelModelo = new javax.swing.JPanel();
        barraRolagem = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelNome = new javax.swing.JLabel();
        LabelMac = new javax.swing.JLabel();
        labelBancada = new javax.swing.JLabel();
        labelPosicao = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        barraprogresso = new javax.swing.JProgressBar();

        tablePanneDialogCliente.setBackground(new java.awt.Color(255, 255, 255));
        tablePanneDialogCliente.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tablePanneDialogCliente.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tablePanneDialogCliente.setOpaque(true);

        painelModelo.setName("teste"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        barraRolagem.setViewportView(jTextArea1);

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNome.setText("Nome:");

        LabelMac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelMac.setText("MAC:");

        labelBancada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelBancada.setText("Bancada");

        labelPosicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPosicao.setText("Posição:");

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        barraprogresso.setToolTipText("completo");
        barraprogresso.setStringPainted(true);

        javax.swing.GroupLayout painelModeloLayout = new javax.swing.GroupLayout(painelModelo);
        painelModelo.setLayout(painelModeloLayout);
        painelModeloLayout.setHorizontalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraRolagem)
                    .addGroup(painelModeloLayout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(LabelMac, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(labelBancada, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(labelPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModeloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(barraprogresso, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelModeloLayout.setVerticalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBancada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar))
                .addGap(7, 7, 7)
                .addComponent(barraprogresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablePanneDialogCliente.addTab("MAC:", painelModelo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanneDialogCliente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanneDialogCliente)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMac;
    private javax.swing.JScrollPane barraRolagem;
    public static javax.swing.JProgressBar barraprogresso;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelBancada;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPosicao;
    private javax.swing.JPanel painelModelo;
    public static javax.swing.JTabbedPane tablePanneDialogCliente;
    // End of variables declaration//GEN-END:variables
}
