/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Iniciar;

import Servicos.ExecucaoAtividadesTela;
import Servicos.Instancias;
import Servicos.WakeOnLan;
import configs.comandosServerCliente;
import java.awt.event.MouseEvent;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB01
 */
public class painel extends javax.swing.JPanel {

    /**
     * Creates new form painel1
     */
    boolean dark_aplicado = false;

    public painel() {
        initComponents();
    }

    void enviar() {

        String receptor = labelMaquina.getText();

        if (receptor.startsWith("Bancada:")) {
            Servicos.Instancias.getExecucaoAtividadesInstacia().enviarComando(textAreaEnviar, "bc", receptor.replaceAll("Bancada:", ""), permissaoAceite.isSelected());
        } else if (receptor.startsWith("Setor:")) {
            Servicos.Instancias.getExecucaoAtividadesInstacia().enviarComando(textAreaEnviar, "grupo", receptor.replaceAll("Setor:", ""), permissaoAceite.isSelected());
        } else {
            Servicos.Instancias.getExecucaoAtividadesInstacia().enviarComando(textAreaEnviar, "mac", receptor.replaceAll("Mac:", ""), permissaoAceite.isSelected());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogotextArea = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        areatextoExpandida = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        confirmarbutton = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        menuPopupTextArea = new javax.swing.JPopupMenu();
        expandirCampo = new javax.swing.JMenuItem();
        servicosCliente = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableaServicos = new javax.swing.JTable();
        btnPara = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNomeExi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        mensagem = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaTextoMensagem = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        telaCadastro = new javax.swing.JDialog();
        macselecionado = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        setorCadastro = new javax.swing.JTextField();
        bancadabox = new javax.swing.JComboBox<>();
        posicaobox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        tombocadastro = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        autenticaRede = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        loginRede = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        senhaRede = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        OpcoesSecundarias = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        iniciarServerButton = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelConcAtivas = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInterface = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton20 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnservices = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEnviar = new javax.swing.JTextArea();
        labelMaquina = new javax.swing.JLabel();
        enviarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        permissaoAceite = new javax.swing.JCheckBox();
        labelInfo = new javax.swing.JLabel();
        autentica = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        dialogotextArea.setMinimumSize(new java.awt.Dimension(1049, 773));

        areatextoExpandida.setColumns(20);
        areatextoExpandida.setRows(5);
        jScrollPane3.setViewportView(areatextoExpandida);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Área de comando");

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        confirmarbutton.setText("Confirmar");
        confirmarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarbuttonActionPerformed(evt);
            }
        });

        jButton17.setText("Importar Comandos");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogotextAreaLayout = new javax.swing.GroupLayout(dialogotextArea.getContentPane());
        dialogotextArea.getContentPane().setLayout(dialogotextAreaLayout);
        dialogotextAreaLayout.setHorizontalGroup(
            dialogotextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogotextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogotextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogotextAreaLayout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 730, Short.MAX_VALUE)
                        .addComponent(confirmarbutton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarButton)))
                .addContainerGap())
        );
        dialogotextAreaLayout.setVerticalGroup(
            dialogotextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogotextAreaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogotextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(confirmarbutton)
                    .addComponent(jButton17))
                .addGap(13, 13, 13))
        );

        expandirCampo.setText("Expandir Campo");
        expandirCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandirCampoActionPerformed(evt);
            }
        });
        menuPopupTextArea.add(expandirCampo);

        servicosCliente.setAlwaysOnTop(true);
        servicosCliente.setMinimumSize(new java.awt.Dimension(986, 868));

        tableaServicos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        tableaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nome Exibição", "Nome", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableaServicos.setOpaque(false);
        tableaServicos.setRowHeight(20);
        tableaServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableaServicosMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(tableaServicos);
        if (tableaServicos.getColumnModel().getColumnCount() > 0) {
            tableaServicos.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableaServicos.getColumnModel().getColumn(1).setMaxWidth(300);
            tableaServicos.getColumnModel().getColumn(2).setMinWidth(100);
            tableaServicos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableaServicos.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        btnPara.setText("Parar");
        btnPara.setEnabled(false);

        jLabel9.setText("Nome:");

        labelNome.setText(" ");

        jLabel11.setText("Status:");

        labelNomeExi.setText(" ");

        jLabel12.setText("Nome Exibição:");

        labelStatus.setText(" ");

        javax.swing.GroupLayout servicosClienteLayout = new javax.swing.GroupLayout(servicosCliente.getContentPane());
        servicosCliente.getContentPane().setLayout(servicosClienteLayout);
        servicosClienteLayout.setHorizontalGroup(
            servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicosClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeExi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPara, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        servicosClienteLayout.setVerticalGroup(
            servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicosClienteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnPara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(servicosClienteLayout.createSequentialGroup()
                .addGroup(servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicosClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(servicosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelNomeExi)
                                .addComponent(jLabel11)
                                .addComponent(labelStatus)
                                .addComponent(jLabel12))))
                    .addGroup(servicosClienteLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(labelNome)))
                .addGap(6, 6, 6))
        );

        mensagem.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        mensagem.setAlwaysOnTop(true);
        mensagem.setMinimumSize(new java.awt.Dimension(558, 364));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Mesangem do Administrador");

        areaTextoMensagem.setColumns(20);
        areaTextoMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        areaTextoMensagem.setRows(5);
        areaTextoMensagem.setToolTipText("");
        jScrollPane5.setViewportView(areaTextoMensagem);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mensagemLayout = new javax.swing.GroupLayout(mensagem.getContentPane());
        mensagem.getContentPane().setLayout(mensagemLayout);
        mensagemLayout.setHorizontalGroup(
            mensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mensagemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mensagemLayout.setVerticalGroup(
            mensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );

        telaCadastro.setMinimumSize(new java.awt.Dimension(395, 247));

        jLabel15.setText("Setor");

        jLabel16.setText("Bancada");

        jLabel17.setText("Posição");

        setorCadastro.setText("Laboratório 01");

        bancadabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B00", "B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B09", "B10", "B11", "B12" }));

        posicaobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC00", "PC01", "PC02", "PC03" }));

        jLabel18.setText("Tombo");

        tombocadastro.setText("00000000");
        tombocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombocadastroActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(51, 204, 0));
        jButton14.setText("Cadastrar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 102, 102));
        jButton18.setText("Cancelar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroLayout = new javax.swing.GroupLayout(telaCadastro.getContentPane());
        telaCadastro.getContentPane().setLayout(telaCadastroLayout);
        telaCadastroLayout.setHorizontalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14))
                    .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bancadabox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(telaCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(posicaobox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(macselecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombocadastro))
                            .addGroup(telaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        telaCadastroLayout.setVerticalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(macselecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bancadabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicaobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton18))
                .addContainerGap())
        );

        autenticaRede.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        autenticaRede.setTitle("Autenticar na rede");
        autenticaRede.setAlwaysOnTop(true);
        autenticaRede.setMinimumSize(new java.awt.Dimension(430, 160));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Autenticação na Rede");

        jLabel19.setText("Login");

        jLabel20.setText("Senha");

        jButton19.setText("Autenticar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout autenticaRedeLayout = new javax.swing.GroupLayout(autenticaRede.getContentPane());
        autenticaRede.getContentPane().setLayout(autenticaRedeLayout);
        autenticaRedeLayout.setHorizontalGroup(
            autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticaRedeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(autenticaRedeLayout.createSequentialGroup()
                        .addGroup(autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(autenticaRedeLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(senhaRede, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(autenticaRedeLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginRede, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19)))
                .addContainerGap())
        );
        autenticaRedeLayout.setVerticalGroup(
            autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenticaRedeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autenticaRedeLayout.createSequentialGroup()
                        .addGroup(autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(autenticaRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        OpcoesSecundarias.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        OpcoesSecundarias.setMinimumSize(new java.awt.Dimension(400, 348));

        jButton6.setBackground(new java.awt.Color(0, 204, 102));
        jButton6.setText("Fechar Explorador Arquivos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(0, 204, 102));
        jButton22.setText("Caminho Atualizacao");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcoesSecundariasLayout = new javax.swing.GroupLayout(OpcoesSecundarias.getContentPane());
        OpcoesSecundarias.getContentPane().setLayout(OpcoesSecundariasLayout);
        OpcoesSecundariasLayout.setHorizontalGroup(
            OpcoesSecundariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesSecundariasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        OpcoesSecundariasLayout.setVerticalGroup(
            OpcoesSecundariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesSecundariasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(OpcoesSecundariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iniciarServerButton.setBackground(new java.awt.Color(0, 204, 102));
        iniciarServerButton.setText("Iniciar Servidor");
        iniciarServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarServerButtonActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 204, 102));
        jButton12.setText("Verificar Conexões");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 204, 102));
        jButton13.setText("Ligar Computadores");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel2.setText("Status Servidor:");

        jLabel4.setBackground(new java.awt.Color(255, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Desligado");
        jLabel4.setOpaque(true);

        jLabel6.setText("Porta:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(configs.configuracao.portaConexao+"");
        jLabel7.setOpaque(true);

        jLabel8.setText("Conexões Ativas:");

        labelConcAtivas.setBackground(new java.awt.Color(204, 204, 204));
        labelConcAtivas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConcAtivas.setText("000");
        labelConcAtivas.setOpaque(true);

        jButton15.setBackground(new java.awt.Color(0, 204, 102));
        jButton15.setText("Atualizar Banco");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 204, 102));
        jButton16.setText("Painel de Respostas");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dark Mode", "Atualizar Banco", "Teste de Conexões", "Atualizar Clientes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(iniciarServerButton)
                .addGap(36, 36, 36)
                .addComponent(jButton12)
                .addGap(36, 36, 36)
                .addComponent(jButton13)
                .addGap(36, 36, 36)
                .addComponent(jButton15)
                .addGap(36, 36, 36)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConcAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniciarServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelConcAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tableInterface.setBackground(new java.awt.Color(102, 102, 102));
        tableInterface.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "MAC", "ENDEÇO IP", "GRUPO", "BANCADA", "POSIÇÃO", "STATUS", "ACEITAR COMANDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInterface.setToolTipText("");
        tableInterface.setColumnSelectionAllowed(true);
        tableInterface.getTableHeader().setReorderingAllowed(false);
        tableInterface.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInterfaceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableInterfaceMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableInterface);
        tableInterface.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Máquinas Conectadas");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Selec. Tudo");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox1MousePressed(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton20.setText("reload");
        jButton20.setBorderPainted(false);
        jButton20.setFocusCycleRoot(true);
        jButton20.setFocusPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2)))
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jCheckBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opções de Máquina");

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("Desligar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 102));
        jButton3.setText("Reiniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 102));
        jButton4.setText("Bloquear Tela");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 102));
        jButton5.setText("Bloquear Internet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnservices.setBackground(new java.awt.Color(0, 204, 102));
        btnservices.setText("Serviços do SO");
        btnservices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnservicesActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 102));
        jButton7.setText("Bloquear User");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 204, 102));
        jButton8.setText("Limpeza de Sistema");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 204, 102));
        jButton9.setText("Pesquisar na Web");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 204, 102));
        jButton10.setText("Enviar Mensagem");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 204, 102));
        jButton11.setText("Enviar Arquivo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        textAreaEnviar.setColumns(20);
        textAreaEnviar.setRows(5);
        textAreaEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAreaEnviarMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaEnviar);

        labelMaquina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMaquina.setText("Máquina");
        labelMaquina.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                labelMaquinaInputMethodTextChanged(evt);
            }
        });

        enviarButton.setBackground(new java.awt.Color(0, 204, 102));
        enviarButton.setText("Enviar Para >");
        enviarButton.setEnabled(false);
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comando para máquina");

        permissaoAceite.setText("Permitir que o usuário recuse o comando");
        permissaoAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissaoAceiteActionPerformed(evt);
            }
        });

        labelInfo.setForeground(new java.awt.Color(255, 51, 102));
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelInfo.setText("Desabilitado para enviar comando");

        autentica.setBackground(new java.awt.Color(0, 204, 102));
        autentica.setText("Autenticar na Rede");
        autentica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autenticaActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(0, 204, 102));
        jButton21.setText("Desligar USB");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jToggleButton1.setText(":");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(permissaoAceite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(autentica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnservices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 13, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(permissaoAceite)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnservices, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autentica, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarServerButtonActionPerformed
        // TODO add your handling code here:

        if (iniciarServerButton.getText().equalsIgnoreCase("Iniciar Servidor")) {
            if (Servicos.Instancias.getExecucaoAtividadesInstacia().IniciarServidor()) {
                iniciarServerButton.setText("Desligar Servidor");
                iniciarServerButton.setBackground(new java.awt.Color(255, 0, 51));
                jLabel4.setText("Ligado");
                jLabel4.setBackground(new java.awt.Color(0, 204, 102));

            }
        } else {
            if (Servicos.Instancias.getExecucaoAtividadesInstacia().DeligarServer()) {
                iniciarServerButton.setText("Iniciar Servidor");
                iniciarServerButton.setBackground(new java.awt.Color(0, 204, 102));
                jLabel4.setText("Desligado");
                jLabel4.setBackground(new java.awt.Color(255, 0, 51));
            }
        }

    }//GEN-LAST:event_iniciarServerButtonActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        //ExecucaoAtividadesTela.removerTabPanne("10-62-E5-DD-08-4C");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        WakeOnLan.ligarMac();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Servicos.Instancias.getControlebaseIntancia().importarDados();
        Servicos.Instancias.getControlebaseIntancia().atualizarListadeConectados();
        Servicos.Instancias.getCarregarTableInstacia().tabelaConectados();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void tableInterfaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInterfaceMousePressed
        int linha = tableInterface.getSelectedRow();
        int coluna = tableInterface.getSelectedColumn();
        JCheckBox box = new JCheckBox("", (boolean) tableInterface.getValueAt(linha, 7));
        boolean marcado_envio = !box.isSelected();

        labelInfo.setText(" ");

        if (coluna == 3) {
            labelMaquina.setText("Setor:" + tableInterface.getValueAt(linha, 3).toString());
        } else if (coluna == 4) {
            JLabel label = (JLabel) tableInterface.getValueAt(linha, 4);
            labelMaquina.setText("Bancada:" + label.getText());
        } else {
            labelMaquina.setText("Mac:" + tableInterface.getValueAt(linha, 1).toString());
            ExecucaoAtividadesTela.selectTablePane(tableInterface.getValueAt(linha, 1).toString());
        }

        if (coluna == 7) {
            ExecucaoAtividadesTela.setHabilitarEnvioMaquina(marcado_envio, labelMaquina.getText().replaceAll("Mac:", ""));
        }

        if (labelMaquina.getText().contains("=")) {
            enviarButton.setEnabled(false);
            labelInfo.setText("Desabilitado para enviar comando");

        } else {
            DefaultTableModel modelo = (DefaultTableModel) tableInterface.getModel();
            Boolean habilitado = (Boolean) modelo.getValueAt(linha, 7);

            if (habilitado) {

                enviarButton.setEnabled(true);
                labelInfo.setText(" ");
            } else {
                enviarButton.setEnabled(false);
                labelInfo.setText("Desabilitado para enviar comando");
            }

        }

    }//GEN-LAST:event_tableInterfaceMousePressed

    private void jCheckBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MousePressed

    }//GEN-LAST:event_jCheckBox1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jButton1.getText().equalsIgnoreCase("Desligar")) {
            configs.comandosServerCliente.desligarPc();
            jButton1.setText("Cancelar Desligar");
        } else {
            configs.comandosServerCliente.cacelarDesligarPc();
            jButton1.setText("Desligar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jButton3.getText().equalsIgnoreCase("Reiniciar")) {
            configs.comandosServerCliente.ReiniciarPc();
            jButton3.setText("Cancelar Reiniciar");
        } else {
            configs.comandosServerCliente.cancelarReiniciarPc();
            jButton3.setText("Reiniciar");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jButton4.getText().equalsIgnoreCase("Bloquear Tela")) {
            configs.comandosServerCliente.bloquearTela();
            jButton4.setText("Desbloquear Tela");
        } else {
            configs.comandosServerCliente.DesbloquearTela();
            jButton4.setText("Bloquear Tela");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jButton5.getText().equalsIgnoreCase("Bloquear Internet")) {
            configs.comandosServerCliente.bloquearInternet();
            jButton5.setText("Desbloquear Internet");
        } else {
            configs.comandosServerCliente.DesbloquearInternet();
            jButton5.setText("Bloquear Internet");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnservicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnservicesActionPerformed
        textAreaEnviar.setText("liserv:");
        enviar();
        this.servicosCliente.setVisible(true);

    }//GEN-LAST:event_btnservicesActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        configs.comandosServerCliente.bloquearUser();
        //jButton7.setText("Desbloquear User");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        configs.comandosServerCliente.LimparPc();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String link = JOptionPane.showInputDialog("Insira o link para acesso");
        configs.comandosServerCliente.pesquisarWeb(link);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!labelMaquina.getText().contains("Máquina")) {
            this.mensagem.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma máquuina selecionada!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
        ExecucaoAtividadesTela.enviarArquivo(labelMaquina.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        enviar();
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void permissaoAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissaoAceiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permissaoAceiteActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        areatextoExpandida.setText("");
        dialogotextArea.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void confirmarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarbuttonActionPerformed
        // TODO add your handling code here:
        textAreaEnviar.setText(areatextoExpandida.getText());
        dialogotextArea.dispose();
    }//GEN-LAST:event_confirmarbuttonActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        ExecucaoAtividadesTela.importarListaComandos();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void expandirCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandirCampoActionPerformed
        areatextoExpandida.setText(textAreaEnviar.getText());
        dialogotextArea.setVisible(true);
    }//GEN-LAST:event_expandirCampoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Servicos.Instancias.getCarregarTableInstacia().selecTodos(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Instancias.getClientesConctadosTela().setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void textAreaEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaEnviarMousePressed
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            menuPopupTextArea.show(textAreaEnviar, (evt.getX()) + 15, evt.getY() - 20);
        }
    }//GEN-LAST:event_textAreaEnviarMousePressed

    private void tableaServicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableaServicosMousePressed
        btnPara.setEnabled(false);
        int linha = tableaServicos.getSelectedRow();
        labelNome.setText(tableaServicos.getValueAt(linha, 1).toString());
        labelNomeExi.setText(tableaServicos.getValueAt(linha, 0).toString());
        String status = tableaServicos.getValueAt(linha, 2).toString();

        labelStatus.setText(status);

        if (status.contains("Stopped")) {
            btnPara.setEnabled(true);
            btnPara.setText("Iniciar");

        } else if (status.replaceAll(" ", "").isEmpty()) {
            btnPara.setEnabled(false);
            btnPara.setText("Iniciar");
        } else {
            btnPara.setEnabled(true);
            btnPara.setText("Parar");
        }
    }//GEN-LAST:event_tableaServicosMousePressed

    private void labelMaquinaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_labelMaquinaInputMethodTextChanged
        System.out.println("texto alterado");        // TODO add your handling code here:
    }//GEN-LAST:event_labelMaquinaInputMethodTextChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ExecucaoAtividadesTela.enviarMensagemTexto(labelMaquina.getText(), areaTextoMensagem);
        mensagem.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableInterfaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInterfaceMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            int linha = tableInterface.getSelectedRow();
            macselecionado.setText(tableInterface.getValueAt(linha, 1).toString());
            telaCadastro.setVisible(true);
        }
    }//GEN-LAST:event_tableInterfaceMouseClicked

    private void tombocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombocadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombocadastroActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        telaCadastro.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Servicos.Instancias.getControlebaseIntancia().cadastrar(macselecionado.getText(), bancadabox.getSelectedItem().toString().toUpperCase(),
                posicaobox.getSelectedItem().toString().toUpperCase(), tombocadastro.getText(), setorCadastro.getText().toUpperCase());
        telaCadastro.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void autenticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autenticaActionPerformed
        autenticaRede.setLocationRelativeTo(null);
        autenticaRede.setVisible(true);
    }//GEN-LAST:event_autenticaActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        ExecucaoAtividadesTela.autenticarNaRede(loginRede.getText(), senhaRede.getText());
        autenticaRede.dispose();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed


        if (jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Dark Mode")) {
            if (dark_aplicado == false) {
                jPanel1.setBackground(new java.awt.Color(102, 102, 102));
                jPanel2.setBackground(new java.awt.Color(102, 102, 102));
                jPanel3.setBackground(new java.awt.Color(102, 102, 102));
                this.setBackground(new java.awt.Color(102, 102, 102));
                dark_aplicado = true;
            } else {
                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                this.setBackground(new java.awt.Color(240, 240, 240));
                dark_aplicado = false;
            }

        } else if (jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Atualizar Clientes")) {
            comandosServerCliente.setCaminhoAtualizacao();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        if (jButton21.getText().equalsIgnoreCase("Desligar USB")) {
            configs.comandosServerCliente.setDesligarUSb();
            jButton21.setText("Ativar USB");
        } else {
            configs.comandosServerCliente.setLigarUSb();
            jButton21.setText("Desligar USB");
        }
        
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        OpcoesSecundarias.setLocationRelativeTo(this);
        OpcoesSecundarias.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getText().equalsIgnoreCase("Fechar Explorador Arquivos")) {
            configs.comandosServerCliente.fecharExplorer();
            jButton6.setText("Abrir Explorador Arquivos");
        } else {
            configs.comandosServerCliente.AbrirExplorer();
            jButton6.setText("Fechar Explorador Arquivos");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        configs.comandosServerCliente.setCaminhoAtualizacao();
    }//GEN-LAST:event_jButton22ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog OpcoesSecundarias;
    public static javax.swing.JTextArea areaTextoMensagem;
    public static javax.swing.JTextArea areatextoExpandida;
    private javax.swing.JButton autentica;
    private javax.swing.JDialog autenticaRede;
    private javax.swing.JComboBox<String> bancadabox;
    private javax.swing.JButton btnPara;
    private javax.swing.JButton btnservices;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton confirmarbutton;
    private javax.swing.JDialog dialogotextArea;
    private javax.swing.JButton enviarButton;
    private javax.swing.JMenuItem expandirCampo;
    private javax.swing.JButton iniciarServerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JLabel labelConcAtivas;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelMaquina;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeExi;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField loginRede;
    private javax.swing.JLabel macselecionado;
    private javax.swing.JDialog mensagem;
    private javax.swing.JPopupMenu menuPopupTextArea;
    private javax.swing.JCheckBox permissaoAceite;
    private javax.swing.JComboBox<String> posicaobox;
    private javax.swing.JTextField senhaRede;
    private javax.swing.JDialog servicosCliente;
    private javax.swing.JTextField setorCadastro;
    public static javax.swing.JTable tableInterface;
    public static javax.swing.JTable tableaServicos;
    private javax.swing.JDialog telaCadastro;
    public static javax.swing.JTextArea textAreaEnviar;
    private javax.swing.JTextField tombocadastro;
    // End of variables declaration//GEN-END:variables
}
