/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ControleGlobal.configsControleGlobal;
import Servicos.ServidorClass;
import Servicos.enviaMensagemCliente;
import controleCliente.GereciadorClientes;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.Socket;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import linguagem.textoProjeto;

/**
 *
 * @author WESLLEY
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    private ServidorClass classServidor;
    Saida areaSaidatela;
    enviaMensagemCliente mensagemComando;

    public Tela_Principal() {
        initComponents();
        setIconImage(configsControleGlobal.getIconImage());

        this.aplicarLinguagem();
        this.aplicarConfiguracaoInicial();
        classServidor = new ServidorClass();
        areaSaidatela = new Saida();
        mensagemComando = new enviaMensagemCliente();
        areaSaidatela.setVisible(true);
        areaSaidatela.setVisible(false);

    }

    public void botao() {
        if (campoComando.getText().contains("shutdown -s") || campoComando.getText().contains("shutdown -r")) {
            permitir.setEnabled(true);
        } else {
            permitir.setSelected(false);
            permitir.setEnabled(false);
        }
    }

    private void aplicarLinguagem() {
        System.out.println("Aplicando Linguagem");
        ///Labels
        labelGrupo.setText(textoProjeto.label1Grupo);
        labelMaquina.setText(textoProjeto.label1Maquina);
        labelServidor.setText(textoProjeto.label1Server);
        labelStatusServer.setText(textoProjeto.label1Server);
        ///
    }

    private void aplicarConfiguracaoInicial() {
        //Situação do ServidorClass
        exibeStatusServer("D");
        label1Porta.setText(textoProjeto.label1Porta + configsControleGlobal.portaServidor);
    }

    private void exibeStatusServer(String ligadoDeligado) {
        switch (ligadoDeligado) {
            case "L":
                imprimeStatusSever.setText(textoProjeto.label1StatusServer);
                imprimeStatusSever.setForeground(Color.WHITE);
                imprimeStatusSever.setBackground(new java.awt.Color(0, 216, 92));
                break;
            case "D":
                imprimeStatusSever.setText(textoProjeto.label1StatusServerDesligado);
                imprimeStatusSever.setForeground(Color.BLACK);
                imprimeStatusSever.setBackground(new java.awt.Color(168, 21, 14));
                break;
            default:
                throw new AssertionError();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuPopAreaSaida = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        painel_04_tabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMaquinas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        qtdMaquinas = new javax.swing.JLabel();
        qtdMaquinas1 = new javax.swing.JLabel();
        painel_01 = new javax.swing.JPanel();
        btnNovoGrupo = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        labelGrupo = new javax.swing.JLabel();
        btnExGupo = new javax.swing.JButton();
        labelMaquina = new javax.swing.JLabel();
        labelServidor = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        btnNovoGrupo1 = new javax.swing.JButton();
        btnNovoGrupo2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        painel_02_maquinas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoComando = new javax.swing.JTextField();
        maquinaSelect = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        permitir = new javax.swing.JCheckBox();
        jButton16 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGrupo = new javax.swing.JTable();
        painel_03_saida = new javax.swing.JScrollPane();
        areaSaida = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        labelStatusServer = new javax.swing.JLabel();
        imprimeStatusSever = new javax.swing.JLabel();
        label1Porta = new javax.swing.JLabel();
        labelIP = new javax.swing.JLabel();
        painelServer = new javax.swing.JLabel();
        labelHostname1 = new javax.swing.JLabel();

        jButton5.setText("Bloquear Mouse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MoreCoffe");

        jMenuItem1.setText("Limpar Área de Saida");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuPopAreaSaida.add(jMenuItem1);

        jMenuItem2.setText("Expandir Área de Saida");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuPopAreaSaida.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        painel_04_tabela.setBackground(new java.awt.Color(153, 153, 153));
        painel_04_tabela.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabelaMaquinas.setBackground(new java.awt.Color(255, 255, 204));
        tabelaMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPUTADOR", "ENDEREÇO MAC", "ENDEREÇO IP", "GRUPO", "BANCADA", "Nº PC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMaquinas.setToolTipText("");
        tabelaMaquinas.setColumnSelectionAllowed(true);
        tabelaMaquinas.setOpaque(false);
        tabelaMaquinas.setRowHeight(25);
        tabelaMaquinas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaMaquinas.setShowVerticalLines(true);
        tabelaMaquinas.getTableHeader().setReorderingAllowed(false);
        tabelaMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMaquinasMouseClicked(evt);
            }
        });
        tabelaMaquinas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tabelaMaquinasInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMaquinas);
        tabelaMaquinas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaMaquinas.getColumnModel().getColumnCount() > 0) {
            tabelaMaquinas.getColumnModel().getColumn(4).setMaxWidth(70);
            tabelaMaquinas.getColumnModel().getColumn(5).setMaxWidth(100);
        }
        ((DefaultTableCellRenderer) tabelaMaquinas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Máquinas da Rede");

        qtdMaquinas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        qtdMaquinas.setForeground(new java.awt.Color(255, 255, 255));
        qtdMaquinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdMaquinas.setText("0");

        qtdMaquinas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        qtdMaquinas1.setForeground(new java.awt.Color(255, 255, 255));
        qtdMaquinas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdMaquinas1.setText(" ");

        javax.swing.GroupLayout painel_04_tabelaLayout = new javax.swing.GroupLayout(painel_04_tabela);
        painel_04_tabela.setLayout(painel_04_tabelaLayout);
        painel_04_tabelaLayout.setHorizontalGroup(
            painel_04_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_04_tabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_04_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(painel_04_tabelaLayout.createSequentialGroup()
                        .addComponent(qtdMaquinas1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        painel_04_tabelaLayout.setVerticalGroup(
            painel_04_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_04_tabelaLayout.createSequentialGroup()
                .addGroup(painel_04_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtdMaquinas)
                    .addComponent(qtdMaquinas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        painel_04_tabelaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, qtdMaquinas});

        painel_01.setBackground(new java.awt.Color(153, 153, 153));
        painel_01.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNovoGrupo.setBackground(new java.awt.Color(112, 4, 142));
        btnNovoGrupo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNovoGrupo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoGrupo.setText(textoProjeto.btn1NovoGrupo);
        btnNovoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoGrupoActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(168, 21, 14));
        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText(textoProjeto.btn1LigarServer);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        labelGrupo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelGrupo.setForeground(new java.awt.Color(255, 255, 255));
        labelGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGrupo.setText("Grupos");

        btnExGupo.setBackground(new java.awt.Color(112, 4, 142));
        btnExGupo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExGupo.setForeground(new java.awt.Color(255, 255, 255));
        btnExGupo.setText(textoProjeto.btn1ExcluirGrupo);

        labelMaquina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMaquina.setForeground(new java.awt.Color(255, 255, 255));
        labelMaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaquina.setText("Máquinas");

        labelServidor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelServidor.setForeground(new java.awt.Color(255, 255, 255));
        labelServidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServidor.setText("Servidor");

        jButton10.setBackground(new java.awt.Color(168, 21, 14));
        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText(textoProjeto.btn1DesligarServer);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnNovoGrupo1.setBackground(new java.awt.Color(112, 4, 142));
        btnNovoGrupo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNovoGrupo1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoGrupo1.setText(textoProjeto.btn1NovaMaquina);
        btnNovoGrupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoGrupo1ActionPerformed(evt);
            }
        });

        btnNovoGrupo2.setBackground(new java.awt.Color(112, 4, 142));
        btnNovoGrupo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNovoGrupo2.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoGrupo2.setText(textoProjeto.btn1ExcluirMaquina);
        btnNovoGrupo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoGrupo2ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(168, 21, 14));
        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText(textoProjeto.btn1VerificarConexoes);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_01Layout = new javax.swing.GroupLayout(painel_01);
        painel_01.setLayout(painel_01Layout);
        painel_01Layout.setHorizontalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addComponent(btnNovoGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExGupo)))
                .addGap(24, 24, 24)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addComponent(btnNovoGrupo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoGrupo2))
                    .addComponent(labelMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12))
                    .addComponent(labelServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(387, Short.MAX_VALUE))
        );

        painel_01Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExGupo, btnNovoGrupo, btnNovoGrupo1, btnNovoGrupo2, jButton10, jButton9});

        painel_01Layout.setVerticalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(labelMaquina)
                    .addComponent(labelServidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExGupo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoGrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painel_02_maquinas.setBackground(new java.awt.Color(153, 153, 153));
        painel_02_maquinas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Opções da Máquina");

        jButton1.setBackground(new java.awt.Color(143, 16, 247));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText(textoProjeto.btn2Desligar);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(143, 16, 247));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Bloquear Teclado e Mouse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(143, 16, 247));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText(textoProjeto.btn2Reiniciar);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(143, 16, 247));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Bloquear Internet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(143, 16, 247));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Boquear User");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(143, 16, 247));
        jButton13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Executar Limpeza"); // NOI18N
        jButton13.setActionCommand("Cancelar  Desligamento");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(143, 16, 247));
        jButton7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Congelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(143, 16, 247));
        jButton8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Descongelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 153, 51));
        jButton14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Enviar >");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comando:");

        campoComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComandoActionPerformed(evt);
            }
        });
        campoComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoComandoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoComandoKeyReleased(evt);
            }
        });

        maquinaSelect.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        maquinaSelect.setForeground(new java.awt.Color(255, 255, 255));
        maquinaSelect.setText(textoProjeto.label2MaquinaSelecionada);

        jButton11.setBackground(new java.awt.Color(143, 16, 247));
        jButton11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText(textoProjeto.btn2BloquarTela);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(143, 16, 247));
        jButton15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText(textoProjeto.btn2DesbloquearTela);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        permitir.setText("Permitir que o agente aceite que o comando seja executado");
        permitir.setEnabled(false);

        jButton16.setBackground(new java.awt.Color(143, 16, 247));
        jButton16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Enviar Mensagem");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_02_maquinasLayout = new javax.swing.GroupLayout(painel_02_maquinas);
        painel_02_maquinas.setLayout(painel_02_maquinasLayout);
        painel_02_maquinasLayout.setHorizontalGroup(
            painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoComando, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton14)
                        .addGap(18, 18, 18)
                        .addComponent(maquinaSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_02_maquinasLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                                    .addComponent(jButton11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_02_maquinasLayout.createSequentialGroup()
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(permitir, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_02_maquinasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton11, jButton13, jButton15, jButton16, jButton2, jButton3, jButton4, jButton6, jButton7, jButton8});

        painel_02_maquinasLayout.setVerticalGroup(
            painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_02_maquinasLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(12, 12, 12)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton15))
                .addGap(12, 12, 12)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(12, 12, 12)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoComando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_02_maquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(maquinaSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permitir))
        );

        painel_02_maquinasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton11, jButton13, jButton15, jButton16, jButton2, jButton3, jButton4, jButton6, jButton7, jButton8});

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane2.setBackground(new java.awt.Color(0, 175, 143));

        tableGrupo.setAutoCreateRowSorter(true);
        tableGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo"
            }
        ));
        tableGrupo.setAlignmentX(1.0F);
        tableGrupo.setAlignmentY(1.0F);
        tableGrupo.setRowHeight(30);
        tableGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGrupoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableGrupo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        painel_03_saida.setBackground(new java.awt.Color(153, 153, 153));
        painel_03_saida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));
        painel_03_saida.setOpaque(true);

        areaSaida.setEditable(false);
        areaSaida.setColumns(20);
        areaSaida.setRows(5);
        areaSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                areaSaidaMousePressed(evt);
            }
        });
        painel_03_saida.setViewportView(areaSaida);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelStatusServer.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelStatusServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatusServer.setText("Status do Servidor");

        imprimeStatusSever.setBackground(new java.awt.Color(0, 153, 51));
        imprimeStatusSever.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        imprimeStatusSever.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imprimeStatusSever.setText(".");
        imprimeStatusSever.setOpaque(true);

        label1Porta.setText("Porta:-- -- -- --");

        labelIP.setText("IP:--- --- --- ---");

        painelServer.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        painelServer.setText("Informações Locais");

        labelHostname1.setText("Nome Host:--- --- --- ---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1Porta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imprimeStatusSever, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(labelStatusServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelHostname1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {imprimeStatusSever, label1Porta, labelHostname1, labelIP, labelStatusServer});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(labelStatusServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimeStatusSever, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1Porta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHostname1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(painel_04_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)
                                .addComponent(painel_02_maquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(painel_03_saida))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(painel_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_04_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_02_maquinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_03_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, painel_03_saida});

        painel_03_saida.getAccessibleContext().setAccessibleName("Saida");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jButton2.getText().equalsIgnoreCase(textoProjeto.btn2BloquearTeclado)) {
            campoComando.setText("bloquearteclado");
        } else {
            campoComando.setText("desbloquearteclado");
        }
        botao();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jButton3.getText().equalsIgnoreCase(textoProjeto.btn2Reiniciar)) {
            campoComando.setText("shutdown -r -f -t 00");
            jButton3.setText(textoProjeto.btn2ReiniciarCancelar);
        } else {
            campoComando.setText("shutdown /a");
            jButton3.setText(textoProjeto.btn2Reiniciar);
        }
        botao();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//netsh interface ip set dns name = \"Ethernet\" static 127.0.0.1
//Reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections" /v DefaultConnectionSettings /t REG_BINARY /d 4600000009000000090000000a000000302e302e302e303a383000000000000000000000000000000000000000000000000000000000000000000000000000000000 /f 
       campoComando.setText("Reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Connections\" /v DefaultConnectionSettings /t REG_BINARY /d 460000000a0000000b0000000a000000302e302e302e303a383000000000000000000000000000000000000000000000000000000000000000000000000000000000 /f");
        botao();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        botao();
        campoComando.setText("congelamentoAtivado");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        campoComando.setText("congelamentoAtivado");

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            /// Ligar ServidorClass
            classServidor.criaServerSocket(configsControleGlobal.portaServidor);

            areaSaida.append(textoProjeto.mensagemServidorIniciadoSucesso);
            label1Porta.setText(textoProjeto.label1Porta + configsControleGlobal.portaServidor);
            labelIP.setText(classServidor.ipLocal());
            labelHostname1.setText(classServidor.hostLocal());
            exibeStatusServer("L");

            new Thread() {
                @Override
                public void run() {
                    while (!ServidorClass.getServerSocket().isClosed()) {
                        try {
                            Socket socket;
                            socket = ServidorClass.getServerSocket().accept();
                            new GereciadorClientes(socket);

                        } catch (Exception e) {
                            areaSaida.append("\nTread no botao ligar02:" + textoProjeto.mensagemErro + e.getMessage());
                        }
//                        if (ServidorClass.getServerSocket().isClosed()) {
//                            break;
//                        }
                    }

                }

            }.start();

        } catch (IOException ex) {
            areaSaida.append("\nTread no botao ligar:" + textoProjeto.mensagemErro + ex.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            classServidor.DesligaServer();
            areaSaida.append(textoProjeto.mensagemSucesso);
            exibeStatusServer("D");
        } catch (Exception ex) {
            areaSaida.append(textoProjeto.mensagemErro + ex.getMessage());
            System.out.println("Erro botao desligar:" + textoProjeto.mensagemErro + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText().equalsIgnoreCase(textoProjeto.btn2Desligar)) {
            campoComando.setText("shutdown -s -f -t 00");
            jButton1.setText(textoProjeto.btn2DesligarCancelar);

        } else {
            campoComando.setText("shutdown /a");
            jButton1.setText(textoProjeto.btn2Desligar);
        }
        botao();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNovoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoGrupoActionPerformed

    private void campoComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComandoActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mensagemComando.enviaMensagem(configsControleGlobal.paramentroComandoCmd, campoComando.getText());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tabelaMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMaquinasMouseClicked
        // TODO add your handling code here:
        int linha = tabelaMaquinas.getSelectedRow();
        int coluna = tabelaMaquinas.getSelectedColumn();
        if (coluna == 3) {
            maquinaSelect.setText(tabelaMaquinas.getValueAt(linha, coluna).toString());
        } else if (coluna == 4) {
            maquinaSelect.setText(tabelaMaquinas.getValueAt(linha, coluna).toString());
        } else {
            maquinaSelect.setText(tabelaMaquinas.getValueAt(linha, 0).toString());
        }
    }//GEN-LAST:event_tabelaMaquinasMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        campoComando.setText("rundll32.exe user32.dll,LockWorkStation");
        botao();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void areaSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaSaidaMousePressed
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            menuPopAreaSaida.show(painel_03_saida, (evt.getX()) + 15, evt.getY() - 20);
        }

    }//GEN-LAST:event_areaSaidaMousePressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        campoComando.setText("\"\\\\adm\\REDE_ACESSO_RESTRITO\\Executar\\ccleaner\\x64\\CCleaner64.exe\" /auto");
        botao();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        campoComando.setText("bloqueioTela");
        botao();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        campoComando.setText("desbloqueioTela");
        botao();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnNovoGrupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoGrupo1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnNovoGrupo1ActionPerformed

    private void btnNovoGrupo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoGrupo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoGrupo2ActionPerformed

    private void tabelaMaquinasInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabelaMaquinasInputMethodTextChanged
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tableGrupo.getModel();
        for (int i = 0; i < tabelaMaquinas.getRowCount(); i++) {

            modelo.addRow(new Object[]{
                //Nome Grupo
                tabelaMaquinas.getValueAt(i, 4).toString()
            });
        }
    }//GEN-LAST:event_tabelaMaquinasInputMethodTextChanged

    private void tableGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGrupoMouseClicked
        // TODO add your handling code here:
        int i = tableGrupo.getSelectedRow();

        maquinaSelect.setText(tableGrupo.getValueAt(0, i).toString());
    }//GEN-LAST:event_tableGrupoMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        areaSaida.setText("");
        Saida.areaSaida02.setText("");
        menuPopAreaSaida.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (!areaSaidatela.isVisible()) {
            areaSaidatela.setVisible(true);
        }
        menuPopAreaSaida.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (maquinaSelect.getText().equalsIgnoreCase(textoProjeto.label2MaquinaSelecionada)) {
            enviaMensagemCliente.verficarCliente();
        } else {
            mensagemComando.enviaMensagem(configsControleGlobal.paramentroVerfificacao, configsControleGlobal.paramentroVerfificacao);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if (!maquinaSelect.getText().equalsIgnoreCase(textoProjeto.label2MaquinaSelecionada)) {
            escreverMensagem mensagem = new escreverMensagem(mensagemComando);
            mensagem.setVisible(true);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void campoComandoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoComandoKeyPressed

    }//GEN-LAST:event_campoComandoKeyPressed

    private void campoComandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoComandoKeyReleased
        System.out.println("Key pressed:" + evt.getKeyCode());
        if (evt.getKeyCode() == 127) {
            System.out.println("Delete");
            campoComando.setText("");
            maquinaSelect.setText(textoProjeto.label2MaquinaSelecionada);
            tabelaMaquinas.clearSelection();

        }
    }//GEN-LAST:event_campoComandoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea areaSaida;
    private javax.swing.JButton btnExGupo;
    private javax.swing.JButton btnNovoGrupo;
    private javax.swing.JButton btnNovoGrupo1;
    private javax.swing.JButton btnNovoGrupo2;
    public static javax.swing.JTextField campoComando;
    private javax.swing.JLabel imprimeStatusSever;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1Porta;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelHostname1;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelMaquina;
    private javax.swing.JLabel labelServidor;
    private javax.swing.JLabel labelStatusServer;
    public static javax.swing.JLabel maquinaSelect;
    private javax.swing.JPopupMenu menuPopAreaSaida;
    private javax.swing.JLabel painelServer;
    private javax.swing.JPanel painel_01;
    private javax.swing.JPanel painel_02_maquinas;
    private javax.swing.JScrollPane painel_03_saida;
    private javax.swing.JPanel painel_04_tabela;
    public static javax.swing.JCheckBox permitir;
    public static javax.swing.JLabel qtdMaquinas;
    public static javax.swing.JLabel qtdMaquinas1;
    public static javax.swing.JTable tabelaMaquinas;
    public static javax.swing.JTable tableGrupo;
    // End of variables declaration//GEN-END:variables
}
